### ISSUE TITLE
open returns a filename, it should return a promise that resolves a File object?

### ISSUE THREAD

**Issue by PaulKinlan** [WICG/writable-files#1]
I would expect anything that blocks the UI or at least has to intereact with the disk to return a promise and the promise will resolve the filename (or a metadata object or event a `File` that has filename and other attributes such as last access time, etc.)

**Comment by drufball** [comment]
This is a good point. I'll sit down with @inexorabletash and @cmumford to add more concrete details around the actual API surface.

**Comment by mkruisselbrink** [comment]
Closing this, the current proposal does return a promise that resolves to some kind of handle. Exact API shape can and will probably change anyway.
