### ISSUE TITLE
FileSystem API

### ISSUE THREAD

**Issue by richardkazuomiller** [WICG/writable-files#11]
This might be a dumb question, but what was wrong with the FileSystem API? It does what it says on the tin: lets web applications read and write to a sandbox section of the user's local file system.

Why didn't everyone just implement that? All I want to do is save a file somewhere and it seems like by now there should be a better way to do that than shoving a blob into IndexedDB.

**Comment by inexorabletash** [comment]
The intent of this proposal is access to non-sandboxed files.

As far as the API goes, using the same file entry/directory entry types is plausible. As far as why other browsers did not implement... apparently there has not been enough demand to push for implementing.

**Comment by richardkazuomiller** [comment]
I see. So this "skips" sandboxed FS and goes straight to full access. Well, as long as I can have an offline-first web app that can read/write/copy files without having to tell the user they have to reopen them every time they load the app, I'll be happy whether it's in a sandbox or not. It seems to me like having a sandboxed area that doesn't require extra permissions – basically IndexedDB for files – would be a good first step though.

Is this going to allow an app to save files somewhere without prompting the user? I'd like to be able to have the user drop an image into the browser window, then copy that file to some arbitrary location for later use.

**Comment by inexorabletash** [comment]
> Is this going to allow an app to save files somewhere without prompting the user?

Granting permission to a web app to have write access to particular files/directories in a way that meets user expectations is the tricky part.

Your scenario of copying the data into a sandbox outside the scope of this this proposal. It is doable today, although (as you note) without a sandboxed filesystem it's clunky.

**Comment by richardkazuomiller** [comment]
> copying the data into a sandbox is outside the scope of this proposal

Is there any chance it could be put into the scope of the proposal? lol

I think it's important to have some place to stage files before asking the user for a place to save them. For example, if I create a new project in GarageBand and drag in a .wav file, that file probably has to get copied somewhere, even though I haven't told GarageBand where to save the project, because it could be to big to hold as a blob in memory and if it's not copied and the original file is deleted the project will get messed up. I'm sure this is the case with a lot of applications. If we're limited to only accessing files explicitly specified by the user, the utility of any file accessing API is limited.

**Comment by inexorabletash** [comment]
> Is there any chance it could be put into the scope of the proposal? 

That would be a proposal for a sandboxed file system API - so you're back to where you started. "what was wrong with the FileSystem API?" &rarr; it was specified and implemented in Chrome but other browsers vendors did not consider it important enough to implement or pursue alternatives. I'd recommend filing feature requests against the non-Chrome browsers asking for the feature.
