### ISSUE TITLE
State that this is obsoleted

### ISSUE THREAD

**Issue by kenchris** [WICG/writable-files#13]
I heard from @mgiuca that this is obsoleted. Could you state that in the README, maybe with an explanation to why this work was abandoned?

**Comment by mgiuca** [comment]
I don't remember saying this. But either way, it looks like no work has happened for over a year.

On the other hand, I think we have an appetite for exploring this soon, with respect to [Ballista](https://github.com/mgiuca/ballista/blob/master/docs/explainer.md) (sites opening files from the native file system, etc).

**Comment by kenchris** [comment]
OK, maybe I understood you wrong then: https://github.com/w3c/manifest/issues/626#issuecomment-367897871 but it doesn't really matter
