### ISSUE TITLE
Supporting "DirectoryReferences" as well as "FileReferences"?

### ISSUE THREAD

**Issue by mccreavy** [WICG/writable-files#6]
Are you considering allowing the user to select/create **Directories** via File.open() API?

If so, would the Promise.open fulfillment callback provide a (TBD) DirectoryReference instead of a FileReference?

I ask because I have a webapp that allow users to select directories via a drag-and-drop "drop" handler:

https://developers.google.com/web/updates/2012/08/Integrating-input-type-file-with-the-Filesystem-API?hl=en

and scan the directory contents for files of interest.

Right now the user is required to "re-drop" a directory to re-scan it for changes between loads of the webapp.  This is not a good experience for the user -- they just want to open the webapp and have it go based on previous configuration.

Also, if the user accidentally closes the webapp before a directory scan is complete (sometimes it may take hours to process a large set of files in the gigabyte range), the webapp can't automatically restart where it was stopped because it no longer has a "DirectoryEntry" from the drop event's dataTransfer member.

I'd be very interested in using your API if it allowed me to maintain a "DirectoryRef" without bothering the user -- please let me know how I can support this effort!

**Comment by mkruisselbrink** [comment]
The latest version of the explainer does in fact have a form of directory references.
